spring:
  profiles:
    active: prod

---

spring:
  profiles: dev
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/indicadb
#    username: postgres
#    password: 1nd1c4
    username: newparus
    password: n3wp@rus
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create" after update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
      fail-on-empty-beans: false

  #File Upload configuration
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  #spring-boot-starter-mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.indicame@gmail.com
    password: indica.me
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        ssl:
          enable: false
        test-connection: true

#File Upload Directory
file:
  upload-dir: ./attachments/

jwt:
  secret: usersecret

---

spring:
  profiles: prod

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create" after update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
      fail-on-empty-beans: false

  #File Upload configuration
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  #spring-boot-starter-mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.indicame@gmail.com
    password: indica.me
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        ssl:
          enable: false
        test-connection: true

#File Upload Directory
file:
  upload-dir: ./attachments/

jwt:
  secret: usersecret
